// lib/models/firebase_options.dart

// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqEjT6Al696smV1KR7XTCdaskdF6rIAMc',
    appId: '1:562965496906:web:49c13fcfb0fc4f87f552b3',
    messagingSenderId: '562965496906',
    projectId: 'ath-celcom-proximity-447d9',
    authDomain: 'ath-celcom-proximity-447d9.firebaseapp.com',
    storageBucket: 'ath-celcom-proximity-447d9.appspot.com',
    measurementId: 'G-GGHTG69J8B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8cGlWdk9MR0Re5fYOKf6N9zM3zewi3eg',
    appId: '1:562965496906:android:8346575a823cc361f552b3',
    messagingSenderId: '562965496906',
    projectId: 'ath-celcom-proximity-447d9',
    storageBucket: 'ath-celcom-proximity-447d9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByHweYW-DAK7CE871QQjrypu0COYYZEXs',
    appId: '1:562965496906:ios:97e2052b06fb8552f552b3',
    messagingSenderId: '562965496906',
    projectId: 'ath-celcom-proximity-447d9',
    storageBucket: 'ath-celcom-proximity-447d9.appspot.com',
    iosBundleId: 'com.ath.proximity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByHweYW-DAK7CE871QQjrypu0COYYZEXs',
    appId: '1:562965496906:ios:97e2052b06fb8552f552b3',
    messagingSenderId: '562965496906',
    projectId: 'ath-celcom-proximity-447d9',
    storageBucket: 'ath-celcom-proximity-447d9.appspot.com',
    iosBundleId: 'com.ath.proximity',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqEjT6Al696smV1KR7XTCdaskdF6rIAMc',
    appId: '1:562965496906:web:5ce043a67004b3bcf552b3',
    messagingSenderId: '562965496906',
    projectId: 'ath-celcom-proximity-447d9',
    authDomain: 'ath-celcom-proximity-447d9.firebaseapp.com',
    storageBucket: 'ath-celcom-proximity-447d9.appspot.com',
    measurementId: 'G-YPK0DH93GX',
  );
}
